services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "9090:80"
      - "9443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - frontend
      - backend

  frontend:
    container_name: frontend
    image: nextapp:1.0.0
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_URL=/api
    depends_on:
      - backend

  backend:
    container_name: backend
    image: flaskapp:1.0.0
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=postgresql://postgres:admin@db:5432/catalog
      - ITEMS_PER_PAGE=10
      - CACHE_TYPE=RedisCache
      - CACHE_REDIS_HOST=redis
      - CACHE_REDIS_PORT=6379
      - CACHE_REDIS_DB=0
    depends_on:
      - db

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"

  db:
    container_name: db
    image: postgres:17.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: catalog
    ports:
      - 5432:5432
    volumes:
      - tech-site_pgdata:/var/lib/postgresql/data

volumes:
  tech-site_pgdata:
    external: true
